- name: Install asdf
  become: false
  ansible.builtin.git:
    repo: "https://github.com/asdf-vm/asdf.git"
    dest: "{{ lookup('env', 'HOME') }}/.asdf"
    single_branch: yes
    version: v0.8.1
  become_user: "{{ ansible_user_id }}"
  tags:
    - install
    - asdf

- name: Source bash profile
  shell: source $HOME/.bash_profile
  tags:
    - asdf

- include: nodejs.yml
  tags:
    - asdf
    - node

- include: ruby.yml
  tags:
    - asdf
    - ruby
