- name: Install asdf
  ansible.builtin.git:
    repo: "https://github.com/asdf-vm/asdf.git"
    dest: "{{ lookup('env', 'HOME') }}/.asdf"
    single_branch: yes
    version: v0.8.1
  tags:
    - install
    - asdf

- name: Grant asdf file permissions
  file:
    path: "{{ lookup('env', 'HOME') }}/.asdf"
    mode: 777
  tags:
    - install
    - asdf

- name: Install asdf plugins
  asdf_plugins:
    - name: "nodejs"
      versions: ["lts", "17.2.0"]
      global: "lts"
    - name: "ruby"
      versions: ["2.5.1", "3.0.2"]
