- name: Install asdf
  ansible.builtin.git:
    repo: "https://github.com/asdf-vm/asdf.git"
    dest: "{{ lookup('env', 'HOME') }}/.asdf"
    single_branch: yes
    version: "{{ asdf_version }}"

- name: Source bash
  shell: ". {{ lookup('env', 'HOME') }}/.asdf/asdf.sh && . {{ lookup('env', 'HOME') }}/.asdf/asdf.fish"

- include_tasks: nodejs.yml

- include_tasks: ruby.yml
