- name: Install asdf
  ansible.builtin.git:
    repo: "https://github.com/asdf-vm/asdf.git"
    dest: "{{ lookup('env', 'HOME') }}/.asdf"
    single_branch: yes
    version: "{{ asdf_version }}"

- name: Source bash profile
  shell: source $HOME/.bash_profile $HOME/.bashrc $HOME/.zshrc

- include: nodejs.yml

- include: ruby.yml
