- name: Install asdf
  ansible.builtin.git:
    repo: "https://github.com/asdf-vm/asdf.git"
    dest: "{{ lookup('env', 'HOME') }}/.asdf"
    single_branch: yes
    version: "{{ asdf_version }}"

- name: Source bash profile
  shell: "source {{ lookup('env', 'HOME') }}/.bashrc"

- name: Source zsh profile
  shell: "source {{ lookup('env', 'HOME') }}/.zshrc"

- include_tasks: nodejs.yml

- include_tasks: ruby.yml
