- name: Install asdf
  become: false
  ansible.builtin.git:
    repo: "https://github.com/asdf-vm/asdf.git"
    dest: "{{ lookup('env', 'HOME') }}/.asdf"
    single_branch: yes
    version: v0.8.1
  become_user: "{{ ansible_user_id }}"
  tags:
    - install
    - asdf

- name: check if nodejs plugin installed
  become: false
  shell: asdf list | grep nodejs
  register: nodejs_plugin_exists
  ignore_errors: true
  tags:
    - asdf
    - nodejs

- name: install nodejs plugin for asdf
  become: false
  shell: asdf plugin-add nodejs
  when: nodejs_plugin_exists is not successful
  tags:
    - asdf
    - nodejs

- name: import pgp keys
  become: false
  shell: bash ~/.asdf/plugins/nodejs/bin/import-release-team-keyring
  when: nodejs_plugin_exists is not successful
  tags:
    - asdf
    - nodejs

- name: check installed nodejs version
  become: false
  shell: "asdf list nodejs | grep {{ nodejs_version }}"
  register: nodejs_version_exists
  ignore_errors: true
  tags:
    - asdf
    - nodejs

- name: install nodejs
  become: false
  shell: "asdf install nodejs {{ nodejs_version }}"
  register: nodejs_installed
  when: nodejs_version_exists is not successful
  tags:
    - asdf
    - nodejs

- name: set global nodejs version
  become: false
  shell: "asdf global nodejs {{ nodejs_version }}"
  when: nodejs_version_exists is successful or nodejs_installed is successful
  tags:
    - asdf
    - nodejs

- name: reshim nodejs
  become: false
  shell: asdf reshim nodejs
  when: nodejs_version_exists is successful or nodejs_installed is successful
  tags:
    - asdf
    - nodejs
