- name: check if ruby plugin is installed
  shell: asdf list | grep ruby
  register: ruby_plugin_exists
  ignore_errors: true

- name: install ruby plugin for asdf
  shell: asdf plugin-add ruby
  when: ruby_plugin_exists is not successful
      
- name: check installed ruby version
  shell: "asdf list ruby | grep {{ ruby_version }}"
  register: ruby_version_exists
  ignore_errors: true

- name: install ruby
  shell: "asdf install ruby {{ ruby_version }}"
  register: ruby_installed
  when: ruby_version_exists is not successful

- name: set global ruby version
  shell: "asdf global ruby {{ ruby_version }}"
  when: ruby_version_exists is successful or ruby_installed is successful

- name: reshim ruby
  shell: asdf reshim ruby
  when: ruby_version_exists is successful or ruby_installed is successful

