- hosts: localhost
  connection: local
  become: true
  vars:
    source_key: "./.ssh/id_ed25519"
    dest_key: "{{ lookup('env', 'HOME') }}/.ssh/id_ed25519"
    personal: "{{ lookup('env', 'HOME') }}/personal"
  pre_tasks:
    - name: Update Apt
      become: true
      apt:
        force_apt_get: true
        update_cache: true
        state: present
      tags:
        - install
        - core
  tasks:
    - include: tasks/core-setup.yml
    - include: tasks/nvim-setup.yml
    - include: tasks/ssh.yml
    - include: tasks/vscode.yml
    - include: tasks/docker.yml
    - include: tasks/fish.yml
    - include: tasks/slack-setup.yml
    - include: tasks/spotify.yml
