- hosts: localhost
  connection: local
  become: true
  vars:
    source_key: "./.ssh/id_ed25519"
    dest_key: "{{ lookup('env', 'HOME') }}/.ssh/id_ed25519"
    personal: "{{ lookup('env', 'HOME') }}/personal"

  pre_tasks:
    - name: Update Pacman
      pacman:
        update_cache: true
        upgrade: true
      tags:
        - install
        - core

    - name: Create the `aur_builder` user
      become: yes
      ansible.builtin.user:
        name: aur_builder
        create_home: yes
        group: wheel

    - name: Allow the `aur_builder` user to run `sudo pacman` without a password
      become: yes
      ansible.builtin.lineinfile:
        path: /etc/sudoers.d/11-install-aur_builder
        line: 'aur_builder ALL=(ALL) NOPASSWD: /usr/bin/pacman'
        create: yes
        validate: 'visudo -cf %s'

  roles:
    - { role: core, tags: core }
    - { role: ssh, tags: ssh }
    - { role: docker, tags: docker }
    - { role: neovim, tags: neovim }
    - { role: git-setup, tags: git }
    - { role: fish, tags: fish }
    - { role: vscode, tags: vscode }
    - { role: stow, tags: stow }
    - { role: asdf, tags: asdf }
