- name: Install Fish
  apt: name=fish
  tags:
    - install
    - productivity
    - dotfiles
    - fish

- name: Change shell to Fish
  shell: chsh -s $(which fish)
  tags:
    - install
    - productivity
    - dotfiles
    - fish

- name: Creating config file
  file:
    path: "~/.config/fish"
    state: directory
  tags:
    - install
    - productivity
    - dotfiles
    - fish

- name: Removing greeting message
  copy:
    dest: "~/.config/fish/config.fish"
    content: |
      set -g -x fish_greeting ''
  tags:
    - install
    - productivity
    - dotfiles
    - fish

- name: Copying starship theme to file
  shell: curl -fsSL https://starship.rs/install.sh -o ~/starship
  tags:
    - install
    - fish
    - starship

- name: Setting permission for file to execute
  file:
    dest: ~/starship
    mode: +x
  tags:
    - install
    - fish
    - starship

- name: Execute and accept starship theme file
  script: ~/starship -y
  tags:
    - install
    - fish
    - starship

- name: Remove starship file
  file:
    state: absent
    path: ~/starship
  tags:
    - install
    - fish

- name: Add starship to fish
  lineinfile:
    path: ~/.config/fish/config.fish
    line: "starship init fish | source"
  tags:
    - install
    - fish
    - dotfiles
    - starship
