- name: Install Core
  become: true
  pacman: 
    name: [git, the_silver_searcher, fzf, unzip, ttf-fira-code, ttf-jetbrains-mono, kitty, zellij, base-devel,
    flameshot, wget, libffi, libyaml, openssl, zlib, python, gcc, make, python-pip, neovim, ripgrep, cmake]

- name: Install snap
  become: true
  pacman:
    name: snapd

- name: Enable snaps
  become: true
  systemd:
    name: snapd
    state: started
    enabled: yes

- name: Install yay
  become: true
  pacman:
    name: yay
    
