- name: Install Core
  become: true
  pacman:
    name:
      [
        git,
        the_silver_searcher,
        fzf,
        unzip,
        ttf-fira-code,
        ttf-jetbrains-mono,
        zellij,
        kitty,
        base-devel,
        flameshot,
        wget,
        libffi,
        libyaml,
        openssl,
        zlib,
        ripgrep,
        cmake,
        neovim,
        exa,
        xclip,
        obsidian,
        flatpak,
        appimagelauncher,
        thunderbird,
        authy,
        fonts,
      ]

- name: Install snap
  become: true
  pacman:
    name: snapd

- name: Enable snaps
  become: true
  systemd:
    name: snapd
    state: started
    enabled: yes

- name: Install yay
  become: true
  pacman:
    name: yay
