- name: check if nodejs plugin installed
  shell: ". {{ lookup('env', 'HOME') }}/.asdf/asdf.sh && asdf list | grep nodejs"
  register: nodejs_plugin_exists
  ignore_errors: true

- name: install nodejs plugin for asdf
  shell: ". {{ lookup('env', 'HOME') }}/.asdf/asdf.sh && asdf plugin-add nodejs"
  when: nodejs_plugin_exists is not successful
      
- name: check installed nodejs version
  shell: ". {{ lookup('env', 'HOME') }}/.asdf/asdf.sh && asdf list nodejs | grep {{ nodejs_version }}"
  register: nodejs_version_exists
  ignore_errors: true

- name: install nodejs
  shell: ". {{ lookup('env', 'HOME') }}/.asdf/asdf.sh && asdf install nodejs {{ nodejs_version }}"
  register: nodejs_installed
  when: nodejs_version_exists is not successful

- name: set global nodejs version
  shell: ". {{ lookup('env', 'HOME') }}/.asdf/asdf.sh && asdf global nodejs {{ nodejs_version }}"
  when: nodejs_version_exists is successful or nodejs_installed is successful

- name: reshim nodejs
  shell: ". {{ lookup('env', 'HOME') }}/.asdf/asdf.sh && asdf reshim nodejs"
  when: nodejs_version_exists is successful or nodejs_installed is successful
