- name: Install stow
  become: true
  pacman:
    name: stow

- name: Clone dotfiles
  ansible.builtin.git:
    repo: "https://github.com/marcioflaviof/.dotfiles.git"
    dest: "{{ lookup('env', 'HOME') }}/.dotfiles"
  become_user: "{{ ansible_user_id }}"

- name: Remove zshrc
  file:
    state: absent
    path: "{{ lookup('env', 'HOME') }}/.zshrc"

- name: Remove bashrc
  file:
    state: absent
    path: "{{ lookup('env', 'HOME') }}/.bashrc"

- name: Stow!
  shell: "cd {{ lookup('env', 'HOME') }}/.dotfiles && stow ."
