- name: Install Fish
  pacman: 
    name: fish
  tags:
    - install
    - productivity
    - fish

- name: Change shell to Fish
  shell: chsh -s $(which fish)
  tags:
    - install
    - productivity
    - fish

- name: Copying starship theme to file
  shell: curl -o starship.sh https://starship.rs/install.sh
  tags:
    - install
    - fish
    - starship

- name: Setting permission for file to execute
  file:
    dest: ./starship.sh
    mode: +x
  tags:
    - install
    - fish
    - starship

- name: Execute and accept starship theme file
  script: ./starship.sh -y
  tags:
    - install
    - fish
    - starship

- name: Remove starship file
  file:
    state: absent
    path: ./starship.sh
  tags:
    - install
    - starship
    - fish
