- name: Install docker using pacman 
  become: true
  pacman:
    name: docker

- name: Enable systemctl docker
  become: true
  service:
    name: docker
    state: started
    enabled: yes

- name: Adding existing user to group Docker
  become: true
  user:
    name: "{{ ansible_user_id }}"
    groups: docker
    append: yes

- name: Install Docker-Compose
  become: true
  pacman:
    name: docker-compose
